### PR TITLE
Fix astroport LPer limit handling

### LINKED ISSUE #73: fix single sided liquidity limit handling on astroport lper
Currently astroport lper errors when the account has more than the limit, but this is wrong. It should provide the limit instead.

### PR DESCRIPTION
**Pull request by keyleu**
Closes #73 

When looking at @bekauz Osmosis LPer PR I realized I was doing the handling of the limit wrong according to the spec. Modified it to LP the limit when the balance is higher instead of erroring.

### CODE REVIEW

**Review by stiiifff — APPROVED** [review]

File: contracts/services/astroport-lper/src/tests.rs [hunk 1]
```diff
@@ -688,23 +688,42 @@ fn provide_single_sided_liquidity_cw20_lp_token() {
...
-            &ExecuteMsg::ProcessAction(ActionsMsgs::ProvideSingleSidedLiquidity {
-                asset: setup.inner.pool_asset1.clone(),
-                limit: Some(Uint128::new(1)),
-                expected_pool_ratio_range: None,
-            }),
-            &[],
-            setup.inner.processor_acc(),
-        )
-        .unwrap_err();
+    let query_balance = |address: &str| -> u128 {
```
Comment (Art3miX) [inline contracts/services/astroport-lper/src/tests.rs:693]: Really should be a helper function somewhere

Comment (keyleu) [reply contracts/services/astroport-lper/src/tests.rs:693]: changing it into the other PR since I have conflicts for this
