### PR TITLE
bug: cctp vault rate fluctuations

### LINKED ISSUE #339: bug: cctp vault rate fluctuations
# Description

In the current implementation of the cctp vault strategy cycle, the strategist funds the withdraw accounts with untrn in order to cover the IBC transfer fees.

Currently, the untrn funding amount is excessive. The unused delta (funded_amount - taken_ibc_fee) remains in the account until it gets swapped into USDC following a legitimate LP exit due to pending withdrawal requests. This way, the excess amount enters into the strategist accounting flow and moves the rate in an unexpected manner.

### PR DESCRIPTION
**Pull request by bekauz**
closes #339 

# Description

This pr reworks the way cctp vault strategist performs the update cycle.

Summary of changes:
- set the vault configuration fees to realistic values (mostly 1%)
- simplify the strategist module by moving the vault-related logic into the cycle
- rework the redemption rate calculation logic

## Summary by CodeRabbit

- **New Features**
  - Added configurable minimum IBC fee for Neutron strategies.
  - Enhanced user balance logging to include starting balances and detailed reports.
  - Introduced Astroport pool swap functionality for token liquidity operations.

- **Improvements**
  - Refined fee configuration for vault operations, increasing deposit, platform, and performance fees to 1%.
  - Improved logging and error handling throughout strategist operations.
  - Refactored strategy logic for clearer asset management and more accurate calculations.
  - Made initial liquidity amounts for Astroport pools configurable.
  - Updated configuration files and addresses for contracts and accounts.
  - Enhanced vault example with asynchronous delays and replaced mining calls with swap operations.

- **Bug Fixes**
  - Corrected strategist ratio representation in fee distribution.

- **Chores**
  - Updated logging verbosity for end-to-end tests.
  - Refreshed contract and validator addresses in configuration files.

- **Refactor**
  - Removed obsolete EthereumVault trait and related code.
  - Adjusted module visibility and streamlined test flows by removing explicit mining steps.

### CODE REVIEW

File: e2e/examples/eth_cctp_vault/strategist/strategy.rs [hunk 1]
```diff
@@ -103,161 +103,262 @@ impl ValenceWorker for Strategy {
...
+        let pending_obligations_uint256 =
+            Uint256::from_be_bytes(assets_to_withdraw_response._0.to_be_bytes());
+        let eth_deposit_acc_usdc_bal =
+            Uint256::from_be_bytes(deposit_acc_usdc_bal_response._0.to_be_bytes());
+
+        let eth_deposit_acc_usdc_bal_u128 =
+            Uint128::from_str(&eth_deposit_acc_usdc_bal.to_string())?;
+        let vault_issued_shares =
+            Uint256::from_be_bytes(vault_issued_shares_response._0.to_be_bytes());
+        let vault_issued_shares_u128 = Uint128::from_str(&vault_issued_shares.to_string())?;
```
Comment (keyleu) [inline e2e/examples/eth_cctp_vault/strategist/strategy.rs:164]: nit: prob should use Uint256 everywhere? Feels weird mixing both. I would go for Uint256 just to be on the same precision. Not a big deal tho.

I generally use alloy U256 for all ethereum balances and if for some reason I need it in cosmwasm I'd convert it to Uint128. Keeping it all in their "real" format

File: justfile [hunk 2]
```diff
@@ -14,7 +14,7 @@ run-example program:
     RUST_LOG=debug cargo run --package {{program}}
 
 run-e2e test:
-    RUST_LOG=debug cargo run --package valence-e2e --example {{test}}
+    RUST_LOG=info cargo run --package valence-e2e --example {{test}}
```
Comment (keyleu) [inline justfile:17]: nice, yeah was manually running this because debug was so annoying lol

**Review by keyleu — COMMENTED** [review]
like discussed in call, I'd consider updating the redemption rate taking into account all assets being swapped back, so slippage would be considered there.
It shouldn't matter if pool is liquid enough that slippage is neglible though

**Review by keyleu — APPROVED** [review]

File: justfile (hunk 2 above)
Comment (bekauz) [reply justfile:17]: I thought it was just me, just this time I forgot to undo it before pushing

File: e2e/examples/eth_cctp_vault/strategist/strategy.rs (hunk 1 above)
Comment (bekauz) [reply e2e/examples/eth_cctp_vault/strategist/strategy.rs:164]: yeah the whole unit conversion logic is a bit of a mess right now. ideally I think it would be nice to have some dedicated helpers package to perform conversions / fixed-point scaling between different domains and all. i'll make an issue for that
